#ifndef CUSTOM_MULS_TILING_KEY_H
#define CUSTOM_MULS_TILING_KEY_H

#define CUSTOM_MULS_KEY_BF16_PROMOTE_FP32 100
#define CUSTOM_MULS_KEY_FP16_PROMOTE_FP32 200
#define CUSTOM_MULS_KEY_FP32_DIRECT 300

#endif // CUSTOM_MULS_TILING_KEY_H
