#!/usr/bin/env python3
"""Step 5: Post the LLM review as a GitHub issue comment.

Reads the review from env (passed via GITHUB_OUTPUT from step 4).
"""

import os

import requests

GITHUB_TOKEN = os.environ["GITHUB_TOKEN"]
REPO = os.environ["REPO"]
ISSUE_NUMBER = os.environ["ISSUE_NUMBER"]
REVIEW = os.environ["REVIEW"]


def post_comment(body: str) -> None:
    url = f"https://api.github.com/repos/{REPO}/issues/{ISSUE_NUMBER}/comments"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json",
    }
    resp = requests.post(url, headers=headers, json={"body": body}, timeout=30)
    resp.raise_for_status()


def main() -> None:
    full_comment = (
        "> This is an automated review generated by the Issue Review Bot. "
        "Feedback is AI-generated and may not be perfect — "
        "maintainers will follow up as needed.\n\n"
        + REVIEW
    )

    print("Posting review comment...")
    post_comment(full_comment)
    print("Done.")


if __name__ == "__main__":
    main()
