#!/usr/bin/env python3
"""Post the review comment and compute label actions.

Supports two modes via ``--kind``:

* ``issue`` — posts issue-specific comment, manages ``need-detail-desc`` label.
* ``pr`` — posts PR-specific comment, manages ``need-detail-desc`` label.

Outputs ``label_actions.json`` for the downstream label-management step.
"""

import argparse
import json
import os
from pathlib import Path

from lib.github_api import get_labels, post_comment

ISSUE_NUMBER = os.environ["ISSUE_NUMBER"]
NEED_DETAIL_LABEL = os.environ.get("NEED_DETAIL_LABEL", "need-detail-desc")


def build_issue_comment(desc_result: dict) -> str:
    """Build the issue review failure comment body."""
    missing_items = desc_result.get("missing_items", [])
    suggestions = desc_result.get("suggestions", [])

    lines = [
        "### Description Completeness Check Result",
        "",
        "The issue description you submitted is incomplete. To help maintainers "
        "locate and resolve the problem more quickly, please provide the following:",
        "",
    ]
    if missing_items:
        lines.append("**Missing items:**")
        for item in missing_items:
            lines.append(f"- {item}")
        lines.append("")
    if suggestions:
        lines.append("**Suggestions:**")
        for item in suggestions:
            lines.append(f"- {item}")
        lines.append("")
    lines.extend(
        [
            "_Content generated by AI, please review carefully._",
            f"_AI score: {desc_result.get('score', '-')}/100_",
        ]
    )
    return "\n".join(lines)


def build_issue_pass_comment(desc_result: dict) -> str:
    """Build a pass-variant issue review comment for flagged→clean transitions."""
    return (
        "### Description Completeness Check Result (Passed)\n\n"
        ":white_check_mark: Description is now complete, thank you for the update!\n\n"
        "_Content generated by AI, please review carefully._"
    )


def build_pr_comment(desc_result: dict) -> str:
    """Build the PR review failure comment body."""
    lines = [
        "## PR Review Check Result",
        "",
        "### Description Completeness Check",
        "",
        "The description is incomplete. To help maintainers locate and resolve "
        "the problem more quickly, please provide the following:",
        "",
    ]
    missing = desc_result.get("missing_items", [])
    if missing:
        lines.append("**Missing items:**")
        for item in missing:
            lines.append(f"- {item}")
        lines.append("")
    suggestions = desc_result.get("suggestions", [])
    if suggestions:
        lines.append("**Suggestions:**")
        for item in suggestions:
            lines.append(f"- {item}")
        lines.append("")
    lines.append(f"_AI score: {desc_result.get('score', '-')}/100_")
    lines.append("")
    lines.append("_Content generated by AI, please review carefully._")
    return "\n".join(lines)


def build_pr_pass_comment(desc_result: dict) -> str:
    """Build a pass-variant PR review comment for flagged→clean transitions."""
    return (
        "## PR Review Check Result (Passed)\n\n"
        ":white_check_mark: Description completeness check passed, thank you for the improvement!\n\n"
        "_Content generated by AI, please review carefully._"
    )


def compute_label_actions(desc_result: dict | None) -> dict:
    """Determine which labels to add and remove."""
    add_labels: list[str] = []
    remove_labels: list[str] = []

    if desc_result:
        desc_executed = desc_result.get("executed", True)
        if desc_executed:
            if desc_result.get("ok", False):
                remove_labels.append(NEED_DETAIL_LABEL)
            else:
                add_labels.append(NEED_DETAIL_LABEL)

    return {"add": add_labels, "remove": remove_labels}


def main() -> None:
    parser = argparse.ArgumentParser(description="Handle review result and post comment")
    parser.add_argument("--input", default="review_result.json", help="Description result JSON")
    parser.add_argument("--label-output", default="label_actions.json", help="File to write label actions JSON to")
    parser.add_argument("--kind", default="issue", choices=["issue", "pr"], help="Target kind: issue or pr")
    args = parser.parse_args()

    input_path = Path(args.input)
    desc_result = json.loads(input_path.read_text()) if input_path.exists() else None

    if desc_result is None:
        print("No description result found, skipping")
        Path(args.label_output).write_text(json.dumps({"add": [], "remove": []}))
        return

    current_labels = get_labels(ISSUE_NUMBER)
    previously_flagged = NEED_DETAIL_LABEL in current_labels

    desc_executed = desc_result.get("executed", True)
    desc_ok = desc_result.get("ok", False)

    if not desc_ok:
        print(f"Posting review comment... (score={desc_result.get('score', 0)})")
        if args.kind == "pr":
            prefix = (
                "> This feedback was auto-generated by the PR Review Bot. "
                "Content generated by AI, please review carefully.\n\n"
            )
            body = build_pr_comment(desc_result)
        else:
            prefix = (
                "> This feedback was auto-generated by the Issue Description Check Bot. "
                "Content generated by AI, please review carefully.\n\n"
            )
            body = build_issue_comment(desc_result)
        post_comment(ISSUE_NUMBER, prefix + body)
    elif desc_executed and previously_flagged:
        print("Posting pass comment...")
        body = build_pr_pass_comment(desc_result) if args.kind == "pr" else build_issue_pass_comment(desc_result)
        post_comment(ISSUE_NUMBER, body)
    else:
        print("Review passed: no comment needed")

    actions = compute_label_actions(desc_result)
    Path(args.label_output).write_text(json.dumps(actions, ensure_ascii=False, indent=2))
    print(f"Label actions: {actions}")


if __name__ == "__main__":
    main()
