#!/usr/bin/python
# -*- coding: utf-8 -*-
# -----------------------------------------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------

import torch

TEST_PARAMS = {
    "decode_first": {
        "Testcase_Name": [None],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [48],
        "S1": [2],
        "S2": [8192],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [1024],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [None],
        "cu_seqlens_q": [None],
        "seqused_ori_kv": [None],
        "seqused_cmp_kv": [None],
        "cu_seqlens_ori_kv": [None],
        "cu_seqlens_cmp_kv": [None],
        "cmp_residual_kv": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [127],
        "ori_win_right": [0],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "template_run_mode": ["CSA"],
        "actlen_mode": ["full"],
        "S1EQS2": [False],
        "return_softmax_lse": [True],
    },
    "prefill_first": {
        "Testcase_Name": [None],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [1],
        "S1": [8192],
        "S2": [8192],
        "N1": [64],
        "N2": [1],
        "D": [512],
        "K": [512],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [None],
        "cu_seqlens_q": [None],
        "seqused_ori_kv": [None],
        "seqused_cmp_kv": [None],
        "cu_seqlens_ori_kv": [None],
        "cu_seqlens_cmp_kv": [None],
        "cmp_residual_kv": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [1],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [0],
        "ori_win_left": [127],
        "ori_win_right": [0],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "template_run_mode": ["SWA"],
        "actlen_mode": ["full"],
        "S1EQS2": [False],
        "return_softmax_lse": [True],
    },
    "ori_sparse_decode": {
        "Testcase_Name": [None],
        "layout_q": ["BSND", "TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [10],
        "S1": [15],
        "S2": [8192],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K1": [124, 64],
        "K": [128],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [None],
        "cu_seqlens_q": [None],
        "seqused_ori_kv": [None],
        "seqused_cmp_kv": [None],
        "cu_seqlens_ori_kv": [None],
        "cu_seqlens_cmp_kv": [None],
        "cmp_residual_kv": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "ori_mask_mode": [0, 3, 4],
        "cmp_mask_mode": [0],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "quant_mode": [1, 2],
        "tile_size": [64],
        "rope_head_dim": [64],
        "template_run_mode": ["ORI_SPARSE"],
        "actlen_mode": ["full"],
        "S1EQS2": [False],
        "ori_kv_topk_mode": ["random"],  # fullK random
        "ori_sparse_indices_mode": ["full"],  # full random
        "ori_topk_length": [None],
        "cmp_topk_length": [None],
        "return_softmax_lse": [True],
    },
    "ori_cmp_sparse_decode": {
        "Testcase_Name": [None],
        "layout_q": ["BSND", "TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [4],
        "S1": [4],
        "S2": [16],
        "N1": [64, 128],
        "N2": [1],
        "D": [512],
        "K": [512],
        "K1": [128],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [None],
        "cu_seqlens_q": [None],
        "seqused_ori_kv": [None],
        "seqused_cmp_kv": [None],
        "cu_seqlens_ori_kv": [None],
        "cu_seqlens_cmp_kv": [None],
        "cmp_residual_kv": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "ori_mask_mode": [0, 3, 4],
        "cmp_mask_mode": [0],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "template_run_mode": ["ORI_SPARSE", "ORI_CMP_SPARSE"],
        "actlen_mode": ["full"],
        "S1EQS2": [False],
        "ori_kv_topk_mode": ["fullK"],  # fullK random
        "cmp_kv_topk_mode": ["fullK"],
        "ori_sparse_indices_mode": ["full"],  # full random
        "cmp_sparse_indices_mode": ["full"],
        "ori_topk_length": [None],
        "cmp_topk_length": [None],
        "return_softmax_lse": [True],
    },
    "ori_sparse_decode_bsnd": {
        "Testcase_Name": [None],
        "layout_q": ["BSND"],
        "layout_kv": ["BSND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [10],
        "S1": [15],
        "S2": [8192],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K1": [64, 32],
        "K": [128],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [None],
        "cu_seqlens_q": [None],
        "seqused_ori_kv": [None],
        "seqused_cmp_kv": [None],
        "cu_seqlens_ori_kv": [None],
        "cu_seqlens_cmp_kv": [None],
        "cmp_residual_kv": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "ori_mask_mode": [0, 3, 4],
        "cmp_mask_mode": [0],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "template_run_mode": ["ORI_SPARSE"],
        "actlen_mode": ["full"],
        "S1EQS2": [False],
        "ori_kv_topk_mode": ["random"],
        "ori_sparse_indices_mode": ["full"],
        "ori_topk_length": [None],
        "cmp_topk_length": [None],
        "return_softmax_lse": [True],
    },
    "ori_cmp_sparse_decode_tnd": {
        "Testcase_Name": [None],
        "layout_q": ["TND"],
        "layout_kv": ["TND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [4],
        "S1": [4],
        "S2": [8192],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [256],
        "K1": [512],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [None],
        "cu_seqlens_q": [[0, 4, 8, 12, 16]],
        "seqused_ori_kv": [[100, 111, 96, 1]],
        "seqused_cmp_kv": [[25, 27, 24, 0]],
        "cu_seqlens_ori_kv": [[0, 128, 256, 384, 512]],
        "cu_seqlens_cmp_kv": [[0, 32, 64, 96, 128]],
        "cmp_residual_kv": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "ori_mask_mode": [0, 3, 4],
        "cmp_mask_mode": [0, 3],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "template_run_mode": ["ORI_CMP_SPARSE"],
        "actlen_mode": ["full"],
        "S1EQS2": [False],
        "ori_kv_topk_mode": ["fullK"],
        "cmp_kv_topk_mode": ["fullK"],
        "ori_sparse_indices_mode": ["full"],
        "cmp_sparse_indices_mode": ["full"],
        "ori_topk_length": [None],
        "cmp_topk_length": [None],
        "return_softmax_lse": [True],
    },
    "ori_cmp_sparse_decode_with_topk": {
        "Testcase_Name": [None],
        "layout_q": ["BSND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [2],
        "S1": [2],
        "S2": [8192],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [256],
        "K1": [128],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [None],
        "cu_seqlens_q": [None],
        "seqused_ori_kv": [None],
        "seqused_cmp_kv": [None],
        "cu_seqlens_ori_kv": [None],
        "cu_seqlens_cmp_kv": [None],
        "cmp_residual_kv": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "ori_mask_mode": [0, 3, 4],
        "cmp_mask_mode": [0, 3],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "template_run_mode": ["ORI_CMP_SPARSE"],
        "actlen_mode": ["full"],
        "S1EQS2": [False],
        "ori_kv_topk_mode": ["fullK"],
        "cmp_kv_topk_mode": ["fullK"],
        "ori_sparse_indices_mode": ["full"],
        "cmp_sparse_indices_mode": ["full"],
        "ori_topk_length": [[64, 32, 48, 16]],
        "cmp_topk_length": [[32, 16, 24, 8]],
        "return_softmax_lse": [True],
    },
    "load_4096_swa_tnd_pa": {
        "Testcase_Name": ["bc_load_4096_swa_tnd_pa"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [2],
        "S1": [2],
        "S2": [4096],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [0],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [[2, 2]],
        "cu_seqlens_q": [None],
        "seqused_ori_kv": [[4096]],
        "seqused_cmp_kv": [None],
        "cu_seqlens_ori_kv": [None],
        "cu_seqlens_cmp_kv": [None],
        "cmp_residual_kv": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [1],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [0],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "template_run_mode": ["SWA"],
        "actlen_mode": ["full"],
        "S1EQS2": [False],
        "return_softmax_lse": [True],
        "batch_consistency": [True],
        "batch_consistency_seed": [20260831],
        "batch_consistency_order": [[1, 0]],
        "batch_consistency_batch_split": [[1, 1]],
        "batch_consistency_mode_batch": [0],
        "batch_consistency_token_split": [[1, 1]],
        "batch_consistency_shape_change": [[1, 0]],
    },
    "load_8192_hca_tnd_tnd": {
        "Testcase_Name": ["bc_load_8192_hca_tnd_tnd"],
        "layout_q": ["TND"],
        "layout_kv": ["TND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [2],
        "S1": [2],
        "S2": [6554],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [0],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [[2, 2]],
        "cu_seqlens_q": [None],
        "seqused_ori_kv": [[6554]],
        "seqused_cmp_kv": [[1638]],
        "cu_seqlens_ori_kv": [None],
        "cu_seqlens_cmp_kv": [None],
        "cmp_residual_kv": [[2]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "ori_mask_mode": [3],
        "cmp_mask_mode": [3],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "template_run_mode": ["HCA"],
        "actlen_mode": ["full"],
        "S1EQS2": [False],
        "return_softmax_lse": [True],
        "batch_consistency": [True],
        "batch_consistency_seed": [20260831],
        "batch_consistency_order": [[1, 0]],
        "batch_consistency_batch_split": [[1, 1]],
        "batch_consistency_mode_batch": [0],
        "batch_consistency_token_split": [[1, 1]],
        "batch_consistency_shape_change": [[1, 0]],
    },
    "load_2048_csa_bsnd_bsnd": {
        "Testcase_Name": ["bc_load_2048_csa_bsnd_bsnd"],
        "layout_q": ["BSND"],
        "layout_kv": ["BSND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [2],
        "S1": [2],
        "S2": [1639],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [409],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [[2, 2]],
        "cu_seqlens_q": [None],
        "seqused_ori_kv": [[1639]],
        "seqused_cmp_kv": [[409]],
        "cu_seqlens_ori_kv": [None],
        "cu_seqlens_cmp_kv": [None],
        "cmp_residual_kv": [[3]],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "ori_mask_mode": [4],
        "cmp_mask_mode": [3],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "template_run_mode": ["CSA"],
        "actlen_mode": ["full"],
        "S1EQS2": [False],
        "return_softmax_lse": [True],
        "batch_consistency": [True],
        "batch_consistency_seed": [20260831],
        "batch_consistency_order": [[1, 0]],
        "batch_consistency_batch_split": [[1, 1]],
        "batch_consistency_mode_batch": [0],
        "batch_consistency_token_split": [[1, 1]],
        "batch_consistency_shape_change": [[1, 0]],
    },
    "load_5120_ori_sparse_bsnd_pa": {
        "Testcase_Name": ["bc_load_5120_ori_sparse_bsnd_pa"],
        "layout_q": ["BSND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [2],
        "S1": [2],
        "S2": [5120],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K1": [5120],
        "K": [0],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [[2, 2]],
        "cu_seqlens_q": [None],
        "seqused_ori_kv": [[5120]],
        "seqused_cmp_kv": [None],
        "cu_seqlens_ori_kv": [None],
        "cu_seqlens_cmp_kv": [None],
        "cmp_residual_kv": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "ori_mask_mode": [0],
        "cmp_mask_mode": [0],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "template_run_mode": ["ORI_SPARSE"],
        "actlen_mode": ["full"],
        "S1EQS2": [False],
        "ori_kv_topk_mode": ["random"],
        "ori_sparse_indices_mode": ["full"],
        "ori_topk_length": [None],
        "cmp_topk_length": [None],
        "return_softmax_lse": [True],
        "batch_consistency": [True],
        "batch_consistency_seed": [20260831],
        "batch_consistency_order": [[1, 0]],
        "batch_consistency_batch_split": [[1, 1]],
        "batch_consistency_mode_batch": [0],
        "batch_consistency_token_split": [[1, 1]],
        "batch_consistency_shape_change": [[1, 0]],
    },
    "load_4096_ori_cmp_sparse_tnd_pa": {
        "Testcase_Name": ["bc_load_4096_ori_cmp_sparse_tnd_pa"],
        "layout_q": ["TND"],
        "layout_kv": ["PA_BBND"],
        "q_type": [torch.bfloat16],
        "ori_kv_type": [torch.float8_e4m3fn],
        "cmp_kv_type": [torch.float8_e4m3fn],
        "B": [2],
        "S1": [2],
        "S2": [3277],
        "N1": [128],
        "N2": [1],
        "D": [512],
        "K": [819],
        "K1": [3277],
        "block_num1": [None],
        "block_num2": [None],
        "block_size1": [128],
        "block_size2": [128],
        "seqused_q": [[2, 2]],
        "cu_seqlens_q": [None],
        "seqused_ori_kv": [[3277]],
        "seqused_cmp_kv": [[819]],
        "cu_seqlens_ori_kv": [None],
        "cu_seqlens_cmp_kv": [None],
        "cmp_residual_kv": [None],
        "softmax_scale": [0.04419417],
        "cmp_ratio": [4],
        "ori_mask_mode": [0],
        "cmp_mask_mode": [0],
        "ori_win_left": [-1],
        "ori_win_right": [-1],
        "quant_mode": [1],
        "tile_size": [64],
        "rope_head_dim": [64],
        "template_run_mode": ["ORI_CMP_SPARSE"],
        "actlen_mode": ["full"],
        "S1EQS2": [False],
        "ori_kv_topk_mode": ["fullK"],
        "cmp_kv_topk_mode": ["fullK"],
        "ori_sparse_indices_mode": ["full"],
        "cmp_sparse_indices_mode": ["full"],
        "ori_topk_length": [[64, 32, 48, 16]],
        "cmp_topk_length": [[32, 16, 24, 8]],
        "return_softmax_lse": [True],
        "batch_consistency": [True],
        "batch_consistency_seed": [20260831],
        "batch_consistency_order": [[1, 0]],
        "batch_consistency_batch_split": [[1, 1]],
        "batch_consistency_mode_batch": [0],
        "batch_consistency_token_split": [[1, 1]],
        "batch_consistency_shape_change": [[1, 0]],
    },
}

ENABLED_PARAMS = [TEST_PARAMS["decode_first"]]
# ENABLED_PARAMS = [TEST_PARAMS[key] for key in TEST_PARAMS.keys()]
