#
# Copyright (c) 2025 Huawei Technologies Co., Ltd. All Rights Reserved.
# Copyright 2023 The vLLM team.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file is a part of the vllm-ascend project.
# Adapted from vllm/tests/basic_correctness/test_basic_correctness.py
#
"""Compare the short outputs of HF and vLLM when using greedy sampling.

Run `pytest tests/e2e/multicard/long_sequence/test_prefix_caching_cp.py`
"""

import os
from typing import Any, Dict

import pytest

from tests.e2e.conftest import _LONG_PROMPTS, VllmRunner
from tests.e2e.model_utils import check_outputs_equal
from vllm_ascend.utils import vllm_version_is

os.environ["HCCL_BUFFSIZE"] = "768"

MODELS = [
    "vllm-ascend/Qwen3-30B-A3B-W8A8", "deepseek-ai/DeepSeek-V2-Lite-Chat"
]

SETTINGS: Dict[str, Dict[str, Any]] = {
    "vllm-ascend/Qwen3-30B-A3B-W8A8": {
        "TP": 2,
        "PCP": 2,
        "DCP": 1,
        "quantization": "ascend",
    },
    "deepseek-ai/DeepSeek-V2-Lite-Chat": {
        "TP": 2,
        "PCP": 2,
        "DCP": 2,
        "quantization": None,
    }
}

# A prompt containing a large markdown table. The table is randomly generated by GPT-4.
with open(_LONG_PROMPTS[0], 'r', encoding='utf-8') as file:
    LONG_PROMPT = file.read()

INPUT_PROMPTS = [
    LONG_PROMPT +
    "Question: what is the age of John Doe? Your answer: The age of John Doe is ",
    LONG_PROMPT +
    "Question: what is the age of Alice Johnson? Your answer: The age of Alice Johnson is "
]


@pytest.mark.skipif(vllm_version_is('0.12.0'),
                    reason="0.12.0 is not supported for context sequence.")
@pytest.mark.parametrize("model", MODELS)
@pytest.mark.parametrize("max_tokens", [50])
def test_models_prefix_cache_with_cp_basic(model: str,
                                           max_tokens: int) -> None:
    with VllmRunner(
            model,
            block_size=128,
            max_model_len=4096,
            enforce_eager=True,
            enable_expert_parallel=True,
            enable_prefix_caching=True,
            tensor_parallel_size=SETTINGS[model]['TP'],
            quantization=SETTINGS[model]["quantization"],
            prefill_context_parallel_size=SETTINGS[model]['PCP'],
            decode_context_parallel_size=SETTINGS[model]['DCP']) as vllm_model:
        prefix_cache_output = vllm_model.generate_greedy(
            INPUT_PROMPTS, max_tokens)

    with VllmRunner(
            model,
            block_size=128,
            max_model_len=4096,
            enforce_eager=True,
            enable_expert_parallel=True,
            enable_prefix_caching=False,
            tensor_parallel_size=SETTINGS[model]['TP'],
            quantization=SETTINGS[model]["quantization"],
            prefill_context_parallel_size=SETTINGS[model]['PCP'],
            decode_context_parallel_size=SETTINGS[model]['DCP']) as vllm_model:
        vllm_output = vllm_model.generate_greedy(INPUT_PROMPTS, max_tokens)
    check_outputs_equal(
        outputs_0_lst=vllm_output,
        outputs_1_lst=prefix_cache_output,
        name_0="vllm_output",
        name_1="prefix_cache_output",
    )


@pytest.mark.skipif(vllm_version_is('0.12.0'),
                    reason="0.12.0 is not supported for context sequence.")
@pytest.mark.parametrize("model", MODELS)
@pytest.mark.parametrize("max_tokens", [50])
def test_models_prefix_cache_with_cp_piecewise(model: str,
                                               max_tokens: int) -> None:
    with VllmRunner(
            model,
            block_size=128,
            max_model_len=4096,
            enforce_eager=False,
            enable_expert_parallel=True,
            enable_prefix_caching=True,
            tensor_parallel_size=SETTINGS[model]['TP'],
            quantization=SETTINGS[model]["quantization"],
            prefill_context_parallel_size=SETTINGS[model]['PCP'],
            decode_context_parallel_size=SETTINGS[model]['DCP']) as vllm_model:
        prefix_cache_output = vllm_model.generate_greedy(
            INPUT_PROMPTS, max_tokens)

    with VllmRunner(
            model,
            block_size=128,
            max_model_len=4096,
            enforce_eager=True,
            enable_expert_parallel=True,
            enable_prefix_caching=False,
            tensor_parallel_size=SETTINGS[model]['TP'],
            quantization=SETTINGS[model]["quantization"],
            prefill_context_parallel_size=SETTINGS[model]['PCP'],
            decode_context_parallel_size=SETTINGS[model]['DCP']) as vllm_model:
        vllm_output = vllm_model.generate_greedy(INPUT_PROMPTS, max_tokens)
    check_outputs_equal(
        outputs_0_lst=vllm_output,
        outputs_1_lst=prefix_cache_output,
        name_0="vllm_output",
        name_1="prefix_cache_output",
    )


@pytest.mark.skipif(vllm_version_is('0.12.0'),
                    reason="0.12.0 is not supported for context sequence.")
@pytest.mark.parametrize("model", MODELS)
@pytest.mark.parametrize("max_tokens", [50])
def test_models_prefix_cache_with_cp_full_graph(model: str,
                                                max_tokens: int) -> None:
    with VllmRunner(model,
                    block_size=128,
                    max_model_len=4096,
                    enforce_eager=False,
                    enable_expert_parallel=True,
                    enable_prefix_caching=True,
                    tensor_parallel_size=SETTINGS[model]['TP'],
                    quantization=SETTINGS[model]["quantization"],
                    prefill_context_parallel_size=SETTINGS[model]['PCP'],
                    decode_context_parallel_size=SETTINGS[model]['DCP'],
                    compilation_config={
                        "cudagraph_capture_sizes": [4, 8, 24, 48, 60],
                        "cudagraph_mode": "FULL_DECODE_ONLY"
                    }) as vllm_model:
        prefix_cache_output = vllm_model.generate_greedy(
            INPUT_PROMPTS, max_tokens)

    with VllmRunner(model,
                    block_size=128,
                    max_model_len=4096,
                    enforce_eager=False,
                    enable_expert_parallel=True,
                    enable_prefix_caching=False,
                    tensor_parallel_size=SETTINGS[model]['TP'],
                    quantization=SETTINGS[model]["quantization"],
                    prefill_context_parallel_size=SETTINGS[model]['PCP'],
                    decode_context_parallel_size=SETTINGS[model]['DCP'],
                    compilation_config={
                        "cudagraph_capture_sizes": [4, 8, 24, 48, 60],
                        "cudagraph_mode": "FULL_DECODE_ONLY"
                    }) as vllm_model:
        vllm_output = vllm_model.generate_greedy(INPUT_PROMPTS, max_tokens)
    check_outputs_equal(
        outputs_0_lst=vllm_output,
        outputs_1_lst=prefix_cache_output,
        name_0="vllm_output",
        name_1="prefix_cache_output",
    )
