name: 🤗 Support request for new model supported from huggingface/modelscope/modelers on Ascend
description: Submit a proposal/request for a new model from huggingface/modelscope/modelers on Ascend
title: "[New Model]: "
labels: ["new model"]

body:
- type: markdown
  attributes:
    value: >
      #### Before submitting an issue, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/vllm-project/vllm-ascend/issues?q=is%3Aissue+sort%3Acreated-desc+).

      #### We also highly recommend you read https://vllm-ascend.readthedocs.io/en/latest/user_guide/supported_models.html first to know which model already supported.
- type: textarea
  attributes:
    label: The model to consider.
    description: >
      A huggingface/modelscope/modelers url, pointing to the model, e.g. https://huggingface.co/openai-community/gpt2 .
  validations:
    required: true
- type: textarea
  attributes:
    label: The closest model vllm already supports.
    description: >
      Here is the list of models already supported by vllm: https://vllm-ascend.readthedocs.io/en/latest/user_guide/supported_models.html . Which model is the most similar to the model you want to add support for?
- type: textarea
  attributes:
    label: What's your difficulty of supporting the model you want?
    description: >
      For example, any new operators or new architecture?
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
