e2e-upstream_singlecard:
  - name: tests/entrypoints/openai/chat_completion/test_chat_echo.py
    estimated_time: 20
  - name: tests/entrypoints/scale_out/token_in_token_out/test_serving_tokens.py
    estimated_time: 20
  - name: tests/entrypoints/openai/chat_completion/test_chat_echo.py
    estimated_time: 20
  - name: tests/entrypoints/scale_out/token_in_token_out/test_serving_tokens.py
    estimated_time: 20