enable_prefix_caching: true
tensor-parallel-size: 1
data-parallel-size: 1
block-size: 128
max-num-batched-tokens: 8192
port: 8105
max-model-len: 10000
kv-transfer-config: '{
    "kv_connector": "MooncakeConnectorStoreV1",
    "kv_role": "kv_both",
    "kv_connector_extra_config": {
        "mooncake_rpc_port": "0"
    }
}'
