name: 'e2e test pre step'
description: 'environment prepare for e2e test'

inputs:
  vllm:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: prepare environment
      shell: bash
      run: |
        # Check npu and CANN info
        npu-smi info
        cat /usr/local/Ascend/ascend-toolkit/latest/"$(uname -i)"-linux/ascend_toolkit_install.info

        # Config mirrors
        sed -Ei 's@(ports|archive).ubuntu.com@cache-service.nginx-pypi-cache.svc.cluster.local:8081@g' /etc/apt/sources.list
        pip config set global.index-url http://cache-service.nginx-pypi-cache.svc.cluster.local/pypi/simple
        pip config set global.trusted-host cache-service.nginx-pypi-cache.svc.cluster.local

        # Install system dependencies
        apt-get update -y
        apt-get -y install git
        apt-get -y install `cat packages.txt`
        apt-get -y install gcc g++ cmake libnuma-dev

    - name: Checkout vllm-project/vllm repo
      uses: actions/checkout@v6
      with:
        repository: vllm-project/vllm
        ref: ${{ inputs.vllm }}
        path: ./vllm-empty
        fetch-depth: 1

    - name: Install vllm-project/vllm from source
      working-directory: ./vllm-empty
      shell: bash
      run: |
        VLLM_TARGET_DEVICE=empty pip install -e .

    - name: Install vllm-project/vllm-ascend
      env:
        PIP_EXTRA_INDEX_URL: https://mirrors.huaweicloud.com/ascend/repos/pypi
      shell: bash
      run: |
        pip install -r requirements-dev.txt
        pip install -v -e .

    - name: Install Ascend toolkit & triton_ascend
      shell: bash -l {0}
      run: |
        apt-get -y install clang-15
        update-alternatives --install /usr/bin/clang clang /usr/bin/clang-15 20
        update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-15 20
        BISHENG_NAME="Ascend-BiSheng-toolkit_aarch64_20260105.run"
        BISHENG_URL="https://vllm-ascend.obs.cn-north-4.myhuaweicloud.com/vllm-ascend/${BISHENG_NAME}"
        wget -O "${BISHENG_NAME}" "${BISHENG_URL}" && chmod a+x "${BISHENG_NAME}" && "./${BISHENG_NAME}" --install && rm "${BISHENG_NAME}"
        export PATH=/usr/local/Ascend/tools/bishengir/bin:$PATH
        python3 -m pip install -i https://test.pypi.org/simple/ triton-ascend==3.2.0.dev20260105
