#
# Copyright (c) 2025 Huawei Technologies Co., Ltd. All Rights Reserved.
# This file is a part of the vllm-ascend project.
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from __future__ import annotations

import torch
from torch._inductor.pattern_matcher import PatternMatcherPass
from vllm.compilation.passes.vllm_inductor_pass import VllmInductorPass
from vllm.config import VllmConfig
from vllm.config.compilation import Range
from vllm.logger import logger

from vllm_ascend.compilation.passes.base_pattern import BasePattern


class GeluPattern(BasePattern):
    """
    Pattern that matches torch.ops.aten.gelu.default and replaces it with
    an NPU-compatible implementation using torch_npu.npu_gelu.

    This is needed because aten::gelu is not supported on NPU and falls back
    to CPU, which causes errors during graph capture due to host-device
    synchronization restrictions.
    """

    def __init__(self, vllm_config: VllmConfig):
        super().__init__(vllm_config)

    def get_inputs(self) -> list[torch.Tensor]:
        """
        Generate example inputs for the GeluPattern.
        """
        x = torch.randn(2, 2048, device="npu", dtype=self.dtype)
        return [x]

    def get_pattern(self):
        def pattern(x: torch.Tensor):
            """
            Pattern for standard GELU activation.
            Note: We don't pass the approximate argument here to match
            the default case where approximate="none" is used implicitly.
            """
            return torch.ops.aten.gelu.default(x)

        return pattern

    def get_replacement(self):
        def replacement(x: torch.Tensor):
            """
            Replacement that uses NPU-compatible GELU implementation.

            Uses torch_npu.npu_gelu which provides exact GELU computation
            on NPU devices, avoiding the CPU fallback.
            """
            import torch_npu

            return torch_npu.npu_gelu(x)

        return replacement


class GeluInplacePattern(BasePattern):
    """
    Pattern that matches torch.ops.aten.gelu_.default (in-place GELU) and
    replaces it with an NPU-compatible implementation.
    """

    def __init__(self, vllm_config: VllmConfig):
        super().__init__(vllm_config)

    def get_inputs(self) -> list[torch.Tensor]:
        """
        Generate example inputs for the GeluInplacePattern.
        """
        x = torch.randn(2, 2048, device="npu", dtype=self.dtype)
        return [x]

    def get_pattern(self):
        def pattern(x: torch.Tensor):
            """
            Pattern for in-place GELU activation.
            """
            return torch.ops.aten.gelu_.default(x)

        return pattern

    def get_replacement(self):
        def replacement(x: torch.Tensor):
            """
            Replacement that uses NPU-compatible GELU implementation.

            Since npu_gelu is not in-place, we copy the result back.
            """
            import torch_npu

            out = torch_npu.npu_gelu(x)
            x.copy_(out)
            return x

        return replacement


class GeluOutPattern(BasePattern):
    """
    Pattern that matches torch.ops.aten.gelu.out (out-of-place GELU with
    pre-allocated output tensor) and replaces it with an NPU-compatible
    implementation.

    This variant is generated by torch.compile when compiling graphs with
    upfront compilation (e.g., after vllm commit 5569f5218 which stops lazy
    compilation). The signature is:
        aten::gelu.out(Tensor self, *, str approximate="none", Tensor(a!) out)
        -> Tensor(a!)
    """

    def __init__(self, vllm_config: VllmConfig):
        super().__init__(vllm_config)

    def get_inputs(self) -> list[torch.Tensor]:
        """
        Generate example inputs for the GeluOutPattern.
        The order must match how the function is called: gelu.out(x, out=out)
        """
        x = torch.randn(2, 2048, device="npu", dtype=self.dtype)
        out = torch.empty_like(x)
        return [x, out]

    def get_pattern(self):
        def pattern(x: torch.Tensor, out: torch.Tensor):
            """
            Pattern for GELU with output tensor.
            Matches: torch.ops.aten.gelu.out(x, out=out)
            """
            return torch.ops.aten.gelu.out(x, out=out)

        return pattern

    def get_replacement(self):
        def replacement(x: torch.Tensor, out: torch.Tensor):
            """
            Replacement that uses NPU-compatible GELU implementation.

            Computes npu_gelu and copies the result to the output tensor.
            """
            import torch_npu

            result = torch_npu.npu_gelu(x)
            out.copy_(result)
            return out

        return replacement


class GeluReplacementPass(VllmInductorPass):
    """
    A pass that replaces aten::gelu operations with NPU-compatible
    implementations to enable graph capture on Ascend NPU devices.

    Handles three variants:
    - gelu.default: Standard GELU
    - gelu_.default: In-place GELU
    - gelu.out: GELU with pre-allocated output tensor
    """

    def __init__(self, vllm_config: VllmConfig):
        super().__init__(vllm_config)
        self.pattern_match_passes: PatternMatcherPass = PatternMatcherPass(pass_name="gelu_replacement_pass")

        dtype = vllm_config.model_config.dtype
        if dtype not in (torch.float16, torch.bfloat16, torch.float32):
            logger.debug("GELU replacement not enabled: unsupported dtype %s", dtype)
            return

        # Register all GELU patterns
        GeluPattern(vllm_config).register(self.pattern_match_passes)
        GeluInplacePattern(vllm_config).register(self.pattern_match_passes)
        GeluOutPattern(vllm_config).register(self.pattern_match_passes)

    def __call__(self, graph: torch.fx.Graph) -> None:  # type: ignore[override]
        self.begin()
        self.matched_count = self.pattern_match_passes.apply(graph)
        if self.matched_count > 0:
            logger.debug("Replaced %s gelu operations with NPU-compatible version", self.matched_count)
        self.end_and_log()

    def is_applicable_for_range(self, compile_range: Range) -> bool:
        """
        GELU replacement is always applicable for all compile ranges.
        """
        return True
