/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file quant_batch_matmul_v3_x_tiling_key.h
 * \brief Template-key macros + ASCENDC_TPL_SEL dispatch tree for QBMv3.
 * \author Feodor Pisnitchenko
 */

#ifndef QUANT_BATCH_MATMUL_V3_X_TILING_KEY_H
#define QUANT_BATCH_MATMUL_V3_X_TILING_KEY_H

#include "ascendc/host_api/tiling/template_argument.h"

#define QUANT_BATCH_MATMUL_V3_X_NOT_TRANS 0
#define QUANT_BATCH_MATMUL_V3_X_B_TRANS 1
#define QUANT_BATCH_MATMUL_V3_X_A_TRANS 2
#define QUANT_BATCH_MATMUL_V3_X_ALL_TRANS 3

#define QUANT_BATCH_MATMUL_V3_X_KERNEL_TEMPLATE_TYPE_TBE 0
#define QUANT_BATCH_MATMUL_V3_X_KERNEL_TEMPLATE_TYPE_BASIC 1
#define QUANT_BATCH_MATMUL_V3_X_KERNEL_TEMPLATE_TYPE_OPT 2

#define QUANT_BATCH_MATMUL_V3_X_NOT_PERTOKEN 0
#define QUANT_BATCH_MATMUL_V3_X_IS_PERTOKEN 1

#define QUANT_BATCH_MATMUL_V3_X_OPTION_ATTR_NONE 0
#define QUANT_BATCH_MATMUL_V3_X_NEED_ATOMICLEAN 1
#define QUANT_BATCH_MATMUL_V3_X_IS_AICAIV_1_2 2

#define SET_CUBE_ONLY_ATTR_NONE(trans, kernel_template_type, pertoken)                                          \
    ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIC_ONLY),                                                         \
    ASCENDC_TPL_UINT_SEL(TRANS, ASCENDC_TPL_UI_LIST, trans),                                                   \
    ASCENDC_TPL_UINT_SEL(KERNEL_TEMPLATE_TYPE, ASCENDC_TPL_UI_LIST,                                            \
        QUANT_BATCH_MATMUL_V3_X_KERNEL_TEMPLATE_TYPE_##kernel_template_type),                                    \
    ASCENDC_TPL_UINT_SEL(PERTOKEN, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_##pertoken),                    \
    ASCENDC_TPL_UINT_SEL(OPTION_ATTRS, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_OPTION_ATTR_NONE),

// v200 (310P): uses ASCENDC_TPL_AICORE for mixed AIC+AIV pertoken path.
// MIX_AIC_1_1 is invalid on v200; AICORE is the compatible kernel type.
#define SET_V200_PERTOKEN_ATTR_NONE(trans, kernel_template_type, pertoken)                                      \
    ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AICORE),                                                            \
    ASCENDC_TPL_UINT_SEL(TRANS, ASCENDC_TPL_UI_LIST, trans),                                                   \
    ASCENDC_TPL_UINT_SEL(KERNEL_TEMPLATE_TYPE, ASCENDC_TPL_UI_LIST,                                            \
        QUANT_BATCH_MATMUL_V3_X_KERNEL_TEMPLATE_TYPE_##kernel_template_type),                                    \
    ASCENDC_TPL_UINT_SEL(PERTOKEN, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_##pertoken),                    \
    ASCENDC_TPL_UINT_SEL(OPTION_ATTRS, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_OPTION_ATTR_NONE),

// Non-v200 platforms: MIX_AIC_1_1 for mixed AIC+AIV mode.
#define SET_MIX_ATTR_NONE(trans, kernel_template_type, pertoken)                                                \
    ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_1),                                                       \
    ASCENDC_TPL_UINT_SEL(TRANS, ASCENDC_TPL_UI_LIST, trans),                                                   \
    ASCENDC_TPL_UINT_SEL(KERNEL_TEMPLATE_TYPE, ASCENDC_TPL_UI_LIST,                                            \
        QUANT_BATCH_MATMUL_V3_X_KERNEL_TEMPLATE_TYPE_##kernel_template_type),                                    \
    ASCENDC_TPL_UINT_SEL(PERTOKEN, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_##pertoken),                    \
    ASCENDC_TPL_UINT_SEL(OPTION_ATTRS, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_OPTION_ATTR_NONE),

ASCENDC_TPL_ARGS_DECL(
    QuantBatchMatmulV3X,
    ASCENDC_TPL_UINT_DECL(TRANS, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST,
        QUANT_BATCH_MATMUL_V3_X_NOT_TRANS, QUANT_BATCH_MATMUL_V3_X_B_TRANS,
        QUANT_BATCH_MATMUL_V3_X_A_TRANS, QUANT_BATCH_MATMUL_V3_X_ALL_TRANS),
    ASCENDC_TPL_UINT_DECL(KERNEL_TEMPLATE_TYPE, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST,
        QUANT_BATCH_MATMUL_V3_X_KERNEL_TEMPLATE_TYPE_TBE,
        QUANT_BATCH_MATMUL_V3_X_KERNEL_TEMPLATE_TYPE_BASIC,
        QUANT_BATCH_MATMUL_V3_X_KERNEL_TEMPLATE_TYPE_OPT),
    ASCENDC_TPL_UINT_DECL(PERTOKEN, ASCENDC_TPL_1_BW, ASCENDC_TPL_UI_LIST,
        QUANT_BATCH_MATMUL_V3_X_NOT_PERTOKEN, QUANT_BATCH_MATMUL_V3_X_IS_PERTOKEN),
    ASCENDC_TPL_UINT_DECL(OPTION_ATTRS, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST,
        QUANT_BATCH_MATMUL_V3_X_OPTION_ATTR_NONE,
        QUANT_BATCH_MATMUL_V3_X_NEED_ATOMICLEAN,
        QUANT_BATCH_MATMUL_V3_X_IS_AICAIV_1_2), );

ASCENDC_TPL_SEL(
#if defined(__CCE_AICORE__)
#if defined(__CCE_AICORE__) && __CCE_AICORE__ == 200
#if (ORIG_DTYPE_Y == DT_FLOAT16 || ORIG_DTYPE_Y == DT_INT8 || ORIG_DTYPE_Y == DT_INT32)
#if (ORIG_DTYPE_SCALE != DT_FLOAT || ORIG_DTYPE_Y == DT_INT32)
    // int64 scale: no KERNEL_TYPE_SEL (compiler infers)
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(TRANS, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_B_TRANS),
        ASCENDC_TPL_UINT_SEL(KERNEL_TEMPLATE_TYPE, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_KERNEL_TEMPLATE_TYPE_TBE),
        ASCENDC_TPL_UINT_SEL(PERTOKEN, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_NOT_PERTOKEN),
        ASCENDC_TPL_UINT_SEL(OPTION_ATTRS, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_OPTION_ATTR_NONE), ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(TRANS, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_B_TRANS),
        ASCENDC_TPL_UINT_SEL(KERNEL_TEMPLATE_TYPE, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_KERNEL_TEMPLATE_TYPE_TBE),
        ASCENDC_TPL_UINT_SEL(PERTOKEN, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_NOT_PERTOKEN),
        ASCENDC_TPL_UINT_SEL(OPTION_ATTRS, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_NEED_ATOMICLEAN), ),
    // 310P: BASIC + NOT_PERTOKEN -- unified vector dequant path
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(TRANS, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_B_TRANS),
        ASCENDC_TPL_UINT_SEL(KERNEL_TEMPLATE_TYPE, ASCENDC_TPL_UI_LIST,
            QUANT_BATCH_MATMUL_V3_X_KERNEL_TEMPLATE_TYPE_BASIC),
        ASCENDC_TPL_UINT_SEL(PERTOKEN, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_NOT_PERTOKEN),
        ASCENDC_TPL_UINT_SEL(OPTION_ATTRS, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_OPTION_ATTR_NONE), ),
#endif
#if (ORIG_DTYPE_SCALE == DT_FLOAT && ORIG_DTYPE_Y == DT_FLOAT16)
    // float32 scale: all entries need KERNEL_TYPE_SEL (required when pertoken entries use it)
    ASCENDC_TPL_ARGS_SEL(SET_V200_PERTOKEN_ATTR_NONE(QUANT_BATCH_MATMUL_V3_X_B_TRANS, BASIC, NOT_PERTOKEN)),
    ASCENDC_TPL_ARGS_SEL(SET_V200_PERTOKEN_ATTR_NONE(QUANT_BATCH_MATMUL_V3_X_NOT_TRANS, BASIC, IS_PERTOKEN)),
    ASCENDC_TPL_ARGS_SEL(SET_V200_PERTOKEN_ATTR_NONE(QUANT_BATCH_MATMUL_V3_X_A_TRANS, BASIC, IS_PERTOKEN)),
    ASCENDC_TPL_ARGS_SEL(SET_V200_PERTOKEN_ATTR_NONE(QUANT_BATCH_MATMUL_V3_X_B_TRANS, BASIC, IS_PERTOKEN)),
    ASCENDC_TPL_ARGS_SEL(SET_V200_PERTOKEN_ATTR_NONE(QUANT_BATCH_MATMUL_V3_X_ALL_TRANS, BASIC, IS_PERTOKEN)),
#endif
#endif
#endif
#else
    // compile tiling only: keep 310p template set
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(TRANS, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_B_TRANS),
        ASCENDC_TPL_UINT_SEL(KERNEL_TEMPLATE_TYPE, ASCENDC_TPL_UI_LIST,
            QUANT_BATCH_MATMUL_V3_X_KERNEL_TEMPLATE_TYPE_BASIC),
        ASCENDC_TPL_UINT_SEL(PERTOKEN, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_NOT_PERTOKEN),
        ASCENDC_TPL_UINT_SEL(OPTION_ATTRS, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_OPTION_ATTR_NONE), ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(TRANS, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_B_TRANS),
        ASCENDC_TPL_UINT_SEL(KERNEL_TEMPLATE_TYPE, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_KERNEL_TEMPLATE_TYPE_TBE),
        ASCENDC_TPL_UINT_SEL(PERTOKEN, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_NOT_PERTOKEN),
        ASCENDC_TPL_UINT_SEL(OPTION_ATTRS, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_OPTION_ATTR_NONE), ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(TRANS, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_B_TRANS),
        ASCENDC_TPL_UINT_SEL(KERNEL_TEMPLATE_TYPE, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_KERNEL_TEMPLATE_TYPE_TBE),
        ASCENDC_TPL_UINT_SEL(PERTOKEN, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_NOT_PERTOKEN),
        ASCENDC_TPL_UINT_SEL(OPTION_ATTRS, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_X_NEED_ATOMICLEAN), ),
    ASCENDC_TPL_ARGS_SEL(SET_MIX_ATTR_NONE(QUANT_BATCH_MATMUL_V3_X_NOT_TRANS, BASIC, IS_PERTOKEN)),
    ASCENDC_TPL_ARGS_SEL(SET_MIX_ATTR_NONE(QUANT_BATCH_MATMUL_V3_X_A_TRANS, BASIC, IS_PERTOKEN)),
    ASCENDC_TPL_ARGS_SEL(SET_MIX_ATTR_NONE(QUANT_BATCH_MATMUL_V3_X_B_TRANS, BASIC, IS_PERTOKEN)),
    ASCENDC_TPL_ARGS_SEL(SET_MIX_ATTR_NONE(QUANT_BATCH_MATMUL_V3_X_ALL_TRANS, BASIC, IS_PERTOKEN)),
#endif
);
#endif // QUANT_BATCH_MATMUL_V3_X_TILING_KEY_H
