/**
 * Copyright (c) 2026 Tianjin University, Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * the BSD 3-Clause License (the "License").
 */

#ifndef CHUNK_FWD_H_TILING_KEY_H
#define CHUNK_FWD_H_TILING_KEY_H

#ifndef TORCH_MODE
#include "ascendc/host_api/tiling/template_argument.h"
#endif

namespace GDN {

#define CHUNK_FWD_H_TPL_BF16 10
#define CHUNK_FWD_H_TPL_FP32 30

#ifndef TORCH_MODE
ASCENDC_TPL_ARGS_DECL(ChunkFwdH,
    ASCENDC_TPL_DTYPE_DECL(D_T_G, CHUNK_FWD_H_TPL_BF16, CHUNK_FWD_H_TPL_FP32),
    ASCENDC_TPL_UINT_DECL(V_DIM, ASCENDC_TPL_1_BW, ASCENDC_TPL_UI_LIST, 128),
    ASCENDC_TPL_BOOL_DECL(USE_GK, 0, 1),
    ASCENDC_TPL_BOOL_DECL(USE_EXP2, 0, 1),
    ASCENDC_TPL_BOOL_DECL(STATE_FP32, 0, 1),
    ASCENDC_TPL_BOOL_DECL(STATE_V_FIRST, 0, 1),
);

#define CHUNK_FWD_H_TPL_SEL_ONE(G_TYPE, USE_GK_VALUE, USE_EXP2_VALUE, STATE_FP32_VALUE, STATE_V_FIRST_VALUE) \
    ASCENDC_TPL_ARGS_SEL( \
        ASCENDC_TPL_DTYPE_SEL(D_T_G, G_TYPE), \
        ASCENDC_TPL_UINT_SEL(V_DIM, ASCENDC_TPL_UI_LIST, 128), \
        ASCENDC_TPL_BOOL_SEL(USE_GK, USE_GK_VALUE), \
        ASCENDC_TPL_BOOL_SEL(USE_EXP2, USE_EXP2_VALUE), \
        ASCENDC_TPL_BOOL_SEL(STATE_FP32, STATE_FP32_VALUE), \
        ASCENDC_TPL_BOOL_SEL(STATE_V_FIRST, STATE_V_FIRST_VALUE), \
    )

#define CHUNK_FWD_H_TPL_SEL_LAYOUT(G_TYPE, USE_GK_VALUE, USE_EXP2_VALUE, STATE_FP32_VALUE) \
    CHUNK_FWD_H_TPL_SEL_ONE(G_TYPE, USE_GK_VALUE, USE_EXP2_VALUE, STATE_FP32_VALUE, 0), \
    CHUNK_FWD_H_TPL_SEL_ONE(G_TYPE, USE_GK_VALUE, USE_EXP2_VALUE, STATE_FP32_VALUE, 1)

#define CHUNK_FWD_H_TPL_SEL_STATE(G_TYPE, USE_GK_VALUE, USE_EXP2_VALUE) \
    CHUNK_FWD_H_TPL_SEL_LAYOUT(G_TYPE, USE_GK_VALUE, USE_EXP2_VALUE, 0), \
    CHUNK_FWD_H_TPL_SEL_LAYOUT(G_TYPE, USE_GK_VALUE, USE_EXP2_VALUE, 1)

#define CHUNK_FWD_H_TPL_SEL_EXP(G_TYPE, USE_GK_VALUE) \
    CHUNK_FWD_H_TPL_SEL_STATE(G_TYPE, USE_GK_VALUE, 0), \
    CHUNK_FWD_H_TPL_SEL_STATE(G_TYPE, USE_GK_VALUE, 1)

#define CHUNK_FWD_H_TPL_SEL_GATE(G_TYPE) \
    CHUNK_FWD_H_TPL_SEL_EXP(G_TYPE, 0), \
    CHUNK_FWD_H_TPL_SEL_EXP(G_TYPE, 1)

ASCENDC_TPL_SEL(
    CHUNK_FWD_H_TPL_SEL_GATE(CHUNK_FWD_H_TPL_BF16),
    CHUNK_FWD_H_TPL_SEL_GATE(CHUNK_FWD_H_TPL_FP32),
);

#undef CHUNK_FWD_H_TPL_SEL_GATE
#undef CHUNK_FWD_H_TPL_SEL_EXP
#undef CHUNK_FWD_H_TPL_SEL_STATE
#undef CHUNK_FWD_H_TPL_SEL_LAYOUT
#undef CHUNK_FWD_H_TPL_SEL_ONE
#endif

} // namespace GDN

#endif // CHUNK_FWD_H_TILING_KEY_H
