/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#ifndef COMPRESS_NORM_ROPE_TEMPLATE_TILING_KEY_H
#define COMPRESS_NORM_ROPE_TEMPLATE_TILING_KEY_H

#include "ascendc/host_api/tiling/template_argument.h"

#define CNR_TPL_FP32 0
#define CNR_TPL_FP16 1
#define CNR_TPL_BF16 27
#define CNR_TPL_2_BW 2

ASCENDC_TPL_ARGS_DECL(
    compress_norm_rope,
    ASCENDC_TPL_DTYPE_DECL(X_T, CNR_TPL_FP16, CNR_TPL_BF16),
    ASCENDC_TPL_DTYPE_DECL(NORM_T, CNR_TPL_FP16, CNR_TPL_BF16),
    ASCENDC_TPL_DTYPE_DECL(ROPE_T, CNR_TPL_FP32, CNR_TPL_FP16, CNR_TPL_BF16),
    ASCENDC_TPL_UINT_DECL(COFF, CNR_TPL_2_BW, ASCENDC_TPL_UI_LIST, 1, 2),
    ASCENDC_TPL_BOOL_DECL(EMPTY_X, 0, 1),
);

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(X_T, CNR_TPL_BF16),
        ASCENDC_TPL_DTYPE_SEL(NORM_T, CNR_TPL_BF16),
        ASCENDC_TPL_DTYPE_SEL(ROPE_T, CNR_TPL_BF16),
        ASCENDC_TPL_UINT_SEL(COFF, ASCENDC_TPL_UI_LIST, 1, 2),
        ASCENDC_TPL_BOOL_SEL(EMPTY_X, 0, 1),
        ASCENDC_TPL_TILING_STRUCT_SEL(optiling::CompressNormRopeTilingData)),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(X_T, CNR_TPL_BF16),
        ASCENDC_TPL_DTYPE_SEL(NORM_T, CNR_TPL_BF16),
        ASCENDC_TPL_DTYPE_SEL(ROPE_T, CNR_TPL_FP32),
        ASCENDC_TPL_UINT_SEL(COFF, ASCENDC_TPL_UI_LIST, 1, 2),
        ASCENDC_TPL_BOOL_SEL(EMPTY_X, 0, 1),
        ASCENDC_TPL_TILING_STRUCT_SEL(optiling::CompressNormRopeTilingData)),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(X_T, CNR_TPL_FP16),
        ASCENDC_TPL_DTYPE_SEL(NORM_T, CNR_TPL_FP16),
        ASCENDC_TPL_DTYPE_SEL(ROPE_T, CNR_TPL_FP16),
        ASCENDC_TPL_UINT_SEL(COFF, ASCENDC_TPL_UI_LIST, 1, 2),
        ASCENDC_TPL_BOOL_SEL(EMPTY_X, 0, 1),
        ASCENDC_TPL_TILING_STRUCT_SEL(optiling::CompressNormRopeTilingData)),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(X_T, CNR_TPL_FP16),
        ASCENDC_TPL_DTYPE_SEL(NORM_T, CNR_TPL_FP16),
        ASCENDC_TPL_DTYPE_SEL(ROPE_T, CNR_TPL_FP32),
        ASCENDC_TPL_UINT_SEL(COFF, ASCENDC_TPL_UI_LIST, 1, 2),
        ASCENDC_TPL_BOOL_SEL(EMPTY_X, 0, 1),
        ASCENDC_TPL_TILING_STRUCT_SEL(optiling::CompressNormRopeTilingData)),
);

#endif // COMPRESS_NORM_ROPE_TEMPLATE_TILING_KEY_H
