import torch
from vllm.triton_utils import tl, triton


_NUM_VECTOR_CORES_910B3 = 40


@triton.jit(do_not_specialize=["token_count"])
def _vision_qkv_rope_pad_kernel(
    qkv_proj,
    cos_half,
    sin_half,
    q_out,
    k_out,
    v_out,
    token_count,
    NUM_HEADS: tl.constexpr,
    HEAD_DIM: tl.constexpr,
    PADDED_DIM: tl.constexpr,
    HALF_DIM: tl.constexpr,
    HALF_TILE: tl.constexpr,
    PAD_TILE: tl.constexpr,
    BLOCK_T: tl.constexpr,
    NUM_CORES: tl.constexpr,
):
    core_id = tl.program_id(0)
    qkv_token_stride = 3 * NUM_HEADS * HEAD_DIM
    plane_stride = NUM_HEADS * HEAD_DIM
    out_token_stride = NUM_HEADS * PADDED_DIM

    token_block_count = tl.cdiv(token_count, BLOCK_T)
    blocks_per_core = tl.cdiv(token_block_count, NUM_CORES)
    block_start = core_id * blocks_per_core
    block_end = tl.minimum(block_start + blocks_per_core, token_block_count)
    for block_id in tl.range(block_start, block_end):
        token_start = block_id * BLOCK_T

        # Load the half-width tables once per token tile. Boundary padding makes
        # the 64-column DMA safe while retaining the profiled logical width 36.
        p_cos = tl.make_block_ptr(
            cos_half,
            (token_count, HALF_DIM),
            (HALF_DIM, 1),
            (token_start, 0),
            (BLOCK_T, HALF_TILE),
            (1, 0),
        )
        p_sin = tl.make_block_ptr(
            sin_half,
            (token_count, HALF_DIM),
            (HALF_DIM, 1),
            (token_start, 0),
            (BLOCK_T, HALF_TILE),
            (1, 0),
        )
        cos = tl.load(p_cos, boundary_check=(0, 1), padding_option="zero").to(tl.float32)
        sin = tl.load(p_sin, boundary_check=(0, 1), padding_option="zero").to(tl.float32)
        cos = cos[:, None, :]
        sin = sin[:, None, :]

        # Q first/second halves are two contiguous block loads. This avoids the
        # gather generated by a virtual rotate_half index tensor.
        p_q0 = tl.make_block_ptr(
            qkv_proj,
            (token_count, NUM_HEADS, HEAD_DIM),
            (qkv_token_stride, HEAD_DIM, 1),
            (token_start, 0, 0),
            (BLOCK_T, NUM_HEADS, HALF_TILE),
            (2, 1, 0),
        )
        p_q1 = tl.make_block_ptr(
            qkv_proj,
            (token_count, NUM_HEADS, HEAD_DIM),
            (qkv_token_stride, HEAD_DIM, 1),
            (token_start, 0, HALF_DIM),
            (BLOCK_T, NUM_HEADS, HALF_TILE),
            (2, 1, 0),
        )
        q0 = tl.load(p_q0, boundary_check=(0, 2), padding_option="zero").to(tl.float32)
        q1 = tl.load(p_q1, boundary_check=(0, 2), padding_option="zero").to(tl.float32)
        q_rope0 = (q0 * cos - q1 * sin).to(tl.bfloat16)
        q_rope1 = (q1 * cos + q0 * sin).to(tl.bfloat16)

        p_qo0 = tl.make_block_ptr(
            q_out,
            (token_count, NUM_HEADS, PADDED_DIM),
            (out_token_stride, PADDED_DIM, 1),
            (token_start, 0, 0),
            (BLOCK_T, NUM_HEADS, HALF_TILE),
            (2, 1, 0),
        )
        p_qo1 = tl.make_block_ptr(
            q_out,
            (token_count, NUM_HEADS, PADDED_DIM),
            (out_token_stride, PADDED_DIM, 1),
            (token_start, 0, HALF_DIM),
            (BLOCK_T, NUM_HEADS, HALF_TILE),
            (2, 1, 0),
        )
        tl.store(p_qo0, q_rope0, boundary_check=(0, 2))
        tl.store(p_qo1, q_rope1, boundary_check=(0, 2))

        # K has the same contiguous two-half mapping at plane offset H*D.
        p_k0 = tl.make_block_ptr(
            qkv_proj + plane_stride,
            (token_count, NUM_HEADS, HEAD_DIM),
            (qkv_token_stride, HEAD_DIM, 1),
            (token_start, 0, 0),
            (BLOCK_T, NUM_HEADS, HALF_TILE),
            (2, 1, 0),
        )
        p_k1 = tl.make_block_ptr(
            qkv_proj + plane_stride,
            (token_count, NUM_HEADS, HEAD_DIM),
            (qkv_token_stride, HEAD_DIM, 1),
            (token_start, 0, HALF_DIM),
            (BLOCK_T, NUM_HEADS, HALF_TILE),
            (2, 1, 0),
        )
        k0 = tl.load(p_k0, boundary_check=(0, 2), padding_option="zero").to(tl.float32)
        k1 = tl.load(p_k1, boundary_check=(0, 2), padding_option="zero").to(tl.float32)
        k_rope0 = (k0 * cos - k1 * sin).to(tl.bfloat16)
        k_rope1 = (k1 * cos + k0 * sin).to(tl.bfloat16)

        p_ko0 = tl.make_block_ptr(
            k_out,
            (token_count, NUM_HEADS, PADDED_DIM),
            (out_token_stride, PADDED_DIM, 1),
            (token_start, 0, 0),
            (BLOCK_T, NUM_HEADS, HALF_TILE),
            (2, 1, 0),
        )
        p_ko1 = tl.make_block_ptr(
            k_out,
            (token_count, NUM_HEADS, PADDED_DIM),
            (out_token_stride, PADDED_DIM, 1),
            (token_start, 0, HALF_DIM),
            (BLOCK_T, NUM_HEADS, HALF_TILE),
            (2, 1, 0),
        )
        tl.store(p_ko0, k_rope0, boundary_check=(0, 2))
        tl.store(p_ko1, k_rope1, boundary_check=(0, 2))

        # V needs no RoPE; load logical D=72 and let boundary padding form 128.
        p_v = tl.make_block_ptr(
            qkv_proj + 2 * plane_stride,
            (token_count, NUM_HEADS, HEAD_DIM),
            (qkv_token_stride, HEAD_DIM, 1),
            (token_start, 0, 0),
            (BLOCK_T, NUM_HEADS, PADDED_DIM),
            (2, 1, 0),
        )
        p_vo = tl.make_block_ptr(
            v_out,
            (token_count, NUM_HEADS, PADDED_DIM),
            (out_token_stride, PADDED_DIM, 1),
            (token_start, 0, 0),
            (BLOCK_T, NUM_HEADS, PADDED_DIM),
            (2, 1, 0),
        )
        v = tl.load(p_v, boundary_check=(0, 2), padding_option="zero")
        tl.store(p_vo, v, boundary_check=(0, 2))

        # q1/k1 stores cover pad columns 72:99 with zeros. Finish 96:127.
        zero_pad = tl.zeros((BLOCK_T, NUM_HEADS, PAD_TILE), dtype=tl.bfloat16)
        p_qpad = tl.make_block_ptr(
            q_out,
            (token_count, NUM_HEADS, PADDED_DIM),
            (out_token_stride, PADDED_DIM, 1),
            (token_start, 0, PADDED_DIM - PAD_TILE),
            (BLOCK_T, NUM_HEADS, PAD_TILE),
            (2, 1, 0),
        )
        p_kpad = tl.make_block_ptr(
            k_out,
            (token_count, NUM_HEADS, PADDED_DIM),
            (out_token_stride, PADDED_DIM, 1),
            (token_start, 0, PADDED_DIM - PAD_TILE),
            (BLOCK_T, NUM_HEADS, PAD_TILE),
            (2, 1, 0),
        )
        tl.store(p_qpad, zero_pad, boundary_check=(0, 2))
        tl.store(p_kpad, zero_pad, boundary_check=(0, 2))


def vision_qkv_rope_pad(
    qkv_proj: torch.Tensor,
    cos_half: torch.Tensor,
    sin_half: torch.Tensor,
    q_out: torch.Tensor = None,
    k_out: torch.Tensor = None,
    v_out: torch.Tensor = None,
):
    """Generate padded TND Q/K/V tensors consumed directly by FIA.

    Expected production shapes are qkv_proj=[T, 1728] and
    cos_half=sin_half=[T, 36], all contiguous BF16 tensors on Ascend NPU.
    """
    if qkv_proj.ndim != 2 or cos_half.ndim != 2 or sin_half.ndim != 2:
        raise ValueError("all inputs must be rank-2")
    if qkv_proj.shape[1] != 3 * 8 * 72:
        raise ValueError("qkv_proj must have shape [T, 1728]")
    if cos_half.shape != (qkv_proj.shape[0], 36) or sin_half.shape != cos_half.shape:
        raise ValueError("cos_half and sin_half must have shape [T, 36]")
    if not (qkv_proj.is_contiguous() and cos_half.is_contiguous() and sin_half.is_contiguous()):
        raise ValueError("all inputs must be contiguous")
    if not (qkv_proj.dtype == cos_half.dtype == sin_half.dtype == torch.bfloat16):
        raise ValueError("all inputs must be torch.bfloat16")
    if not (qkv_proj.device == cos_half.device == sin_half.device):
        raise ValueError("all inputs must be on the same device")

    token_count = qkv_proj.shape[0]
    out_shape = (token_count, 8, 128)
    provided = (q_out is not None, k_out is not None, v_out is not None)
    if any(provided) and not all(provided):
        raise ValueError("q_out, k_out and v_out must be provided together")
    if not any(provided):
        q_out = torch.empty(out_shape, dtype=qkv_proj.dtype, device=qkv_proj.device)
        k_out = torch.empty(out_shape, dtype=qkv_proj.dtype, device=qkv_proj.device)
        v_out = torch.empty(out_shape, dtype=qkv_proj.dtype, device=qkv_proj.device)
    else:
        for name, out in (("q_out", q_out), ("k_out", k_out), ("v_out", v_out)):
            if out.shape != out_shape:
                raise ValueError(f"{name} must have shape {out_shape}")
            if out.dtype != qkv_proj.dtype or out.device != qkv_proj.device:
                raise ValueError(f"{name} must match the input dtype and device")
            if not out.is_contiguous():
                raise ValueError(f"{name} must be contiguous")

    _vision_qkv_rope_pad_kernel[(_NUM_VECTOR_CORES_910B3,)](
        qkv_proj,
        cos_half,
        sin_half,
        q_out,
        k_out,
        v_out,
        token_count,
        NUM_HEADS=8,
        HEAD_DIM=72,
        PADDED_DIM=128,
        HALF_DIM=36,
        HALF_TILE=64,
        PAD_TILE=32,
        BLOCK_T=4,
        NUM_CORES=_NUM_VECTOR_CORES_910B3,
    )
    return q_out, k_out, v_out
