name: Label on comment

on:
  issue_comment:
    types: [created]

jobs:
  add-label:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/wait-feedback')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Read allowed users
        run: |
          content=$(cat .github/workflows/matchers/allowed-users.json)
          {
            echo "users<<EOF"
            echo "$content"
            echo "EOF"
          } >> $GITHUB_ENV
      - uses: actions/github-script@v7
        with:
          script: |
            const allowedUsers = JSON.parse(process.env.users)
            const commenter = context.payload.comment.user.login
            if (!allowedUsers.includes(commenter)) {
              console.log(`User ${commenter} not allowed`)
              return
            }
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['wait-feedback']
            })