name: test-case-006-download

on:
  workflow_dispatch:

jobs:
  test-download:
    runs-on: linux-aarch64-cpu-2-buildkit-gy006
    container:
      image: swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/vllm-ascend/act-environments-ubuntu:act-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Run GitHub/Gitee download test via squid proxy
        run: sh test-case-006/test-download.sh
